// Auto-generated from destinos.html.
// DO NOT EDIT.

library destinos_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'dart:html';
import 'dart:json' as json;
import 'package:web_ui/web_ui.dart';
import 'package:web_ui/watcher.dart' as watcher;


// Original code


bool permite_edicion = false;
bool modo_insercion  = true;

modificar(){
  permite_edicion = !permite_edicion;
  modo_insercion  = true;
  
  if (permite_edicion){
    query('#btnPermiteEdicion').value = 'Restringir';
    query('#tdatos').classes.clear();
    query('#tdatos').classes.add("tabla_datos_edicion");
  }
  else{
    query('#btnPermiteEdicion').value = 'Modificar';
    query('#tdatos').classes.clear();
    query('#tdatos').classes.add("tabla_datos");
  }
}

class destino{
  int clave;
  String nombredestino;
}

List<destino> lista_destino = new List<destino>();

llena_lista(data){
  lista_destino= new List<destino>();
  List p_lista = json.parse(data);

  for (int i = 0; i <= p_lista.length - 1; i++){
    destino item = new destino();
    item.clave = p_lista[i]['clave'];
    item.nombredestino = p_lista[i]['destino'];

    lista_destino.add(item);
  }

  watcher.dispatch();
}

obtener_lista(){
  HttpRequest.getString('/rest/destinos/destino_obtener_lista').then(llena_lista);
}

destino obtener_entidad(){
  destino p_destino = new destino();
  p_destino.clave = int.parse(query('#clave').value);
  p_destino.nombredestino = query('#nombredestino').value;

  return p_destino;
}

Map obtener_entidad_mapa(){
  Map p_map = new Map();

  p_map['clave'] = query('#clave').value;
  p_map['destino'] = query('#nombredestino').value;

  return p_map;
}

limpia_edits(){
  query('#clave').value = '1';
  query('#nombredestino').value = '';

  query('#nombredestino').focus();
}

agregar(){

  destino p_destino = obtener_entidad();

  if (p_destino.nombredestino.length == 0){
    window.alert('Se necesita capturar el campo nombredestino');
    query('#nombredestino').focus();
  }

  var req = new HttpRequest();
  if (query('#btnAgregar').value == 'Agregar'){
    req.open('POST', '/rest/destinos/destino_insertar');
    req.setRequestHeader('Content-type', 'application/json');
    req.send(json.stringify(obtener_entidad_mapa()));
    req.onReadyStateChange.listen((data){
      if (req.readyState == HttpRequest.DONE && (req.status == 200 || req.status == 0)) {
        p_destino.clave = (json.parse(req.responseText))['clave'];
        lista_destino.add(p_destino);
        watcher.dispatch();
        limpia_edits();
      }
    });
  }
  else{
    req.open('PUT', '/rest/destinos/destino_actualizar');
    req.setRequestHeader('Content-type', 'application/json');
    req.send(json.stringify(obtener_entidad_mapa()));

    destino p_destino_tmp = lista_destino.where((x) => x.clave == p_destino.clave).toList()[0];
    actualiza_destino(p_destino_tmp, p_destino);

    query('#btnAgregar').value = 'Agregar';
    limpia_edits();
  }

  modo_insercion = true;
}

void actualiza_destino(destino p_destino_tmp, destino p_destino){
  p_destino_tmp.clave = p_destino.clave;
  p_destino_tmp.nombredestino = p_destino.nombredestino;
}

eliminar(destino a_destino){
  if (window.confirm('¿Eliminar registro?'))   {

    var req = new HttpRequest();
    req.open('DELETE', '/rest/destinos/destino_eliminar');
    req.setRequestHeader('Content-type', 'application/json');

    Map p_map = new Map();
    p_map['clave'] = a_destino.clave;

    req.send(json.stringify(p_map));
    lista_destino.remove(a_destino);
  }
}

cancelar(){
  limpia_edits();
  modo_insercion = true;
  query('#btnAgregar').value = 'Agregar';
}

despliega_clase(destino a_destino){
  query('#clave').value = a_destino.clave.toString();
  query('#nombredestino').value = a_destino.nombredestino.toString();
  query('#nombredestino').focus();
  query('#btnAgregar').value = 'Editar';
}

editar(destino a_destino){
  despliega_clase(a_destino);
  modo_insercion = false;
 // window.scroll(0, 0);
}

main(){
  obtener_lista();
}
// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;
  final __html0 = new autogenerated.Element.html('<th template="" instantiate="if modo_insercion"></th>'), __html1 = new autogenerated.Element.html('<tr template="" instantiate="if permite_edicion">\n            <th style="display:none;"><input type="text" id="clave" value="0" disabled="disabled"></th>\n            <th><input type="text" id="nombredestino" value=""></th>\n            <th id="__e-6" style="display:none"></th>\n          </tr>'), __html2 = new autogenerated.Element.html('<th template="" instantiate="if permite_edicion"><input type="button" id="btnAgregar" value="Agregar"><template id="__e-4"></template></th>'), __html3 = new autogenerated.Element.html('<input type="button" id="btnCancelar" value="Cancelar">'), __html4 = new autogenerated.Element.html('<tr style="display:none"></tr>'), __html5 = new autogenerated.Element.html('<tr template="" instantiate="if modo_insercion">\n            <td style="display:none;" id="__e-10"></td>\n            <td id="__e-12"></td>\n            <td id="__e-16" style="display:none"></td>\n          </tr>'), __html6 = new autogenerated.Element.html('<td template="" instantiate="if modo_insercion &amp;&amp; permite_edicion"><a href="#" class="boton_eliminar" id="__e-13">x</a>&nbsp;&nbsp;<a href="#" class="boton_editar" id="__e-14">m</a></td>');
  var __e0, __e1, __e19, __e8;
  var __t = new autogenerated.Template(_root);
  __e0 = _root.query('#btnPermiteEdicion');
  __t.listen(__e0.onClick, ($event) { modificar(); });
  __e1 = _root.query('#__e-1');
  __t.conditional(__e1, () => modo_insercion, (__t) {
  __t.add(__html0.clone(true));
  });

  __e8 = _root.query('#__e-8');
  __t.conditional(__e8, () => permite_edicion, (__t) {
    var __e6, __e7;
    __e7 = __html1.clone(true);
    __e6 = __e7.query('#__e-6');
    __t.conditional(__e6, () => permite_edicion, (__t) {
      var __e2, __e4, __e5;
      __e5 = __html2.clone(true);
      __e2 = __e5.query('#btnAgregar');
      __t.listen(__e2.onClick, ($event) { agregar(); });
      __e4 = __e5.query('#__e-4');
      __t.conditional(__e4, () => !modo_insercion, (__t) {
        var __e3;
        __e3 = __html3.clone(true);
        __t.listen(__e3.onClick, ($event) { cancelar(); });
      __t.add(__e3);
      });

    __t.add(__e5);
    });

  __t.add(__e7);
  });

  __e19 = _root.query('#__e-19');
  __t.loop(__e19, () => lista_destino, (item, __t) {
    var __e18;
    __e18 = __html4.clone(true);
    __t.conditional(__e18, () => modo_insercion, (__t) {
      var __e10, __e12, __e16, __e17;
      __e17 = __html5.clone(true);
      __e10 = __e17.query('#__e-10');
      var __binding9 = __t.contentBind(() => item.clave, false);
      __e10.nodes.add(__binding9);
      __e12 = __e17.query('#__e-12');
      var __binding11 = __t.contentBind(() => item.nombredestino, false);
      __e12.nodes.add(__binding11);
      __e16 = __e17.query('#__e-16');
      __t.conditional(__e16, () => modo_insercion && permite_edicion, (__t) {
        var __e13, __e14, __e15;
        __e15 = __html6.clone(true);
        __e13 = __e15.query('#__e-13');
        __t.listen(__e13.onClick, ($event) { eliminar(item); });
        __e14 = __e15.query('#__e-14');
        __t.listen(__e14.onClick, ($event) { editar(item); });
      __t.add(__e15);
      });

    __t.add(__e17);
    });

  __t.addAll([new autogenerated.Text('\n          '),
      __e18,
      new autogenerated.Text('\n        ')]);
  }, isTemplateElement: false);
  __t.create();
  __t.insert();
}

//@ sourceMappingURL=destinos.dart.map